apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hrnetfront"
  namespace: "default"
  labels:
    app: "hrnetfrontend"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hrnetfrontend"
  template:
    metadata:
      labels:
        app: "hrnetfrontend"
    spec:
      containers:
        - name: "hrnetfrontend-1"
          image: "gcr.io/hrnetapp/hrnetfrontend:latest"
          env:
            - name: "VITE_API_URL"
              valueFrom:
                configMapKeyRef:
                  key: "VITE_API_URL"
                  name: "hrnetfrontend-config-vbp2"
            - name: "VITE_PORT"
              valueFrom:
                configMapKeyRef:
                  key: "VITE_PORT"
                  name: "hrnetfrontend-config-vbp2"
