---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "hrnetfront-config-ktar"
  namespace: "default"
  labels:
    app: "hrnetfront"
data:
  VITE_API_URL: "localhost.local"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hrnetfront"
  namespace: "default"
  labels:
    app: "hrnetfront"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hrnetfront"
  template:
    metadata:
      labels:
        app: "hrnetfront"
    spec:
      containers:
        - name: "hrnetfrontend-sha256-1"
          image: "gcr.io/hrnetapp/hrnetfrontend@sha256:0a9b8bac1e03e60a62a88e97775ded4569914435508b43f7cead5e69daa2d37a"
          env:
            - name: "VITE_API_URL"
              valueFrom:
                configMapKeyRef:
                  key: "VITE_API_URL"
                  name: "hrnetfront-config-ktar"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hrnetfront-hpa-weob"
  namespace: "default"
  labels:
    app: "hrnetfront"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "hrnetfront"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
