---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "hrnetfront-config-tisj"
  namespace: "default"
  labels:
    app: "hrnetfront"
data:
  VITE_API_URL: "dev.com/"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hrnetfront"
  namespace: "default"
  labels:
    app: "hrnetfront"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hrnetfront"
  template:
    metadata:
      labels:
        app: "hrnetfront"
    spec:
      containers:
        - name: "hrnetfrontend-sha256-1"
          image: "gcr.io/hrnetapp/hrnetfrontend:latest"
          env:
            - name: "VITE_API_URL"
              valueFrom:
                configMapKeyRef:
                  key: "VITE_API_URL"
                  name: "hrnetfront-config-tisj"
