version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_c
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev:server
  frontend:
    build: ./frontend
    container_name: frontend_c
    environment:
      VITE_PORT: ${VITE_PORT}
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
