version: "3.8"
services:
  backend:
    build: ./backend
    container_name: backend_c
    environment:
      DATABASE_URL: "mongodb+srv://okafrancois:yuYFt4YKfjL7uUAx@workplace.ed4lc85.mongodb.net/hrnetDB?retryWrites=true&w=majority"
      PORT: "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    command: npm run dev:server
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
