apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hrnetapi"
  namespace: "default"
  labels:
    app: "hrnetapi"
spec:
  replicas: 0
  selector:
    matchLabels:
      app: "hrnetapi"
  template:
    metadata:
      labels:
        app: "hrnetapi"
    spec:
      containers:
        - name: "hrnetbackend-sha256-1"
          image: "gcr.io/hrnetapi/hrnetbackend:latest"
          env:
            - name: "DATABASE_URL"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_URL"
                  name: "hrnetapi-config-fqhz"
