---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "hrnetapi"
---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "hrnetbackend-config-hqpn"
  namespace: "hrnetapi"
  labels:
    app: "hrnetbackend"
data:
  DATABASE_URL: "mongodb+srv://okafrancois:yuYFt4YKfjL7uUAx@workplace.ed4lc85.mongodb.net/hrnetDB?retryWrites=true&w=majority"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hrnetbackend"
  namespace: "hrnetapi"
  labels:
    app: "hrnetbackend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hrnetbackend"
  template:
    metadata:
      labels:
        app: "hrnetbackend"
    spec:
      containers:
        - name: "hrnetbackend-1"
          image: "gcr.io/hrnetapi/hrnetbackend:latest"
          env:
            - name: "DATABASE_URL"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_URL"
                  name: "hrnetbackend-config-hqpn"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hrnetbackend-hpa-sbsa"
  namespace: "hrnetapi"
  labels:
    app: "hrnetbackend"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "hrnetbackend"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
