---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "nginx-1-config-vvk7"
  namespace: "default"
  labels:
    app: "nginx-1"
data:
  DATABASE_URL: "mongodb+srv://okafrancois:yuYFt4YKfjL7uUAx@workplace.ed4lc85.mongodb.net/hrnetDB?retryWrites=true&w=majority"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-1"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "nginx-1"
  template:
    metadata:
      labels:
        app: "nginx-1"
    spec:
      containers:
        - name: "hrnetbackend-sha256-1"
          image: "gcr.io/hrnetapi/hrnetbackend@sha256:5456e140d633f51021d861567e4cc6b9fade9dae804f7ba986ea5acc75d610d0"
          env:
            - name: "DATABASE_URL"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_URL"
                  name: "nginx-1-config-vvk7"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nginx-1-hpa-izzy"
  namespace: "default"
  labels:
    app: "nginx-1"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nginx-1"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
