---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "hrnetserver-config-h4r0"
  namespace: "default"
  labels:
    app: "hrnetserver"
data:
  DATABASE_URL: "mongodb+srv://okafrancois:yuYFt4YKfjL7uUAx@workplace.ed4lc85.mongodb.net/hrnetDB?retryWrites=true&w=majority"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hrnetserver"
  namespace: "default"
  labels:
    app: "hrnetserver"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "hrnetserver"
  template:
    metadata:
      labels:
        app: "hrnetserver"
    spec:
      containers:
        - name: "hrnetbackend-sha256-1"
          image: "gcr.io/hrnetapp/hrnetbackend@sha256:f1afcef0ecc0a3f0f99c4ed6d9264680f60b4a26428b1433caa5d8aeda2fb141"
          env:
            - name: "DATABASE_URL"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_URL"
                  name: "hrnetserver-config-h4r0"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hrnetserver-hpa-qqra"
  namespace: "default"
  labels:
    app: "hrnetserver"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "hrnetserver"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
