---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "hrnetapi-config-fqhz"
  namespace: "default"
  labels:
    app: "hrnetapi"
data:
  DATABASE_URL: "mongodb+srv://okafrancois:yuYFt4YKfjL7uUAx@workplace.ed4lc85.mongodb.net/hrnetDB?retryWrites=true&w=majority"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "hrnetapi"
  namespace: "default"
  labels:
    app: "hrnetapi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "hrnetapi"
  template:
    metadata:
      labels:
        app: "hrnetapi"
    spec:
      containers:
        - name: "hrnetbackend-sha256-1"
          image: "gcr.io/hrnetapi/hrnetbackend@sha256:f694b6f39f5e1ed2e587948e55988d9529993526e371c6d4893d8bbe67c5e779"
          env:
            - name: "DATABASE_URL"
              valueFrom:
                configMapKeyRef:
                  key: "DATABASE_URL"
                  name: "hrnetapi-config-fqhz"
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "hrnetapi-hpa-vnm6"
  namespace: "default"
  labels:
    app: "hrnetapi"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "hrnetapi"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: "Resource"
      resource:
        name: "cpu"
        target:
          type: "Utilization"
          averageUtilization: 80
